/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	somethingcontroller_v1alpha1 "sample-extension-apiserver/apis/somethingcontroller/v1alpha1"
	versioned "sample-extension-apiserver/client/clientset/versioned"
	internalinterfaces "sample-extension-apiserver/client/informers/externalversions/internalinterfaces"
	v1alpha1 "sample-extension-apiserver/client/listers/somethingcontroller/v1alpha1"
	time "time"
)

// SomethingInformer provides access to a shared informer and lister for
// Somethings.
type SomethingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SomethingLister
}

type somethingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSomethingInformer constructs a new informer for Something type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSomethingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSomethingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSomethingInformer constructs a new informer for Something type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSomethingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SomethingcontrollerV1alpha1().Somethings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SomethingcontrollerV1alpha1().Somethings(namespace).Watch(options)
			},
		},
		&somethingcontroller_v1alpha1.Something{},
		resyncPeriod,
		indexers,
	)
}

func (f *somethingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSomethingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *somethingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&somethingcontroller_v1alpha1.Something{}, f.defaultInformer)
}

func (f *somethingInformer) Lister() v1alpha1.SomethingLister {
	return v1alpha1.NewSomethingLister(f.Informer().GetIndexer())
}
